# Generated by Django 6.0.5 on 2026-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productallergen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('high_sugar', models.BooleanField(default=False, help_text='Alto en azucar')),
                ('high_sodium', models.BooleanField(default=False, help_text='Alto en sodio')),
                ('high_fat', models.BooleanField(default=False, help_text='Alto en grasa')),
            ],
            options={
                'verbose_name': 'Hecho Nutricional',
                'verbose_name_plural': 'Hechos Nutricionales',
                'db_table': 'nutritionfacts',
                'indexes': [models.Index(fields=['product_name'], name='nutritionfa_product_188a40_idx')],
            },
        ),
    ]
