# Generated by Django 6.0.5 on 2026-05-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
