# Generated by Django 6.0.5 on 2026-05-17 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('NO_CONSUMPTION', 'Sin Consumo (Mediodía)'), ('LOW_BALANCE', 'Saldo Bajo'), ('WEEKLY_SUMMARY', 'Resumen Semanal')], max_length=50)),
                ('trigger_time', models.TimeField(help_text='Hora del día en que se debe disparar la alerta')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, help_text='Última vez que se ejecutó para evitar duplicados en el mismo día', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='school.school')),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alertas',
                'unique_together': {('school', 'alert_type')},
            },
        ),
    ]
