# Generated by Django 6.0.5 on 2026-05-17 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alertconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('CAFETERIA', 'Admin Cafetería'), ('SECRETARIA', 'Secretaría')], default='SECRETARIA', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Colegio',
                'verbose_name_plural': 'Usuarios de Colegio',
                'permissions': [('can_view_dashboard', 'Puede ver dashboard'), ('can_view_notifications', 'Puede ver notificaciones'), ('can_manage_loans', 'Puede gestionar préstamos'), ('can_manage_inventory', 'Puede gestionar inventario')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('type', models.CharField(choices=[('LOAN', 'Préstamo'), ('STOCK', 'Stock'), ('ALLERGEN', 'Alérgeno'), ('BALANCE', 'Saldo'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, help_text='URL para accion relacionada', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales (JSON)', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school.schooluser')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='school_noti_school__dc9dd8_idx'), models.Index(fields=['user', 'is_read'], name='school_noti_user_id_ca5454_idx'), models.Index(fields=['priority', '-created_at'], name='school_noti_priorit_d6a556_idx')],
            },
        ),
    ]
