# Generated by Django 6.0.5 on 2026-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schooluser_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica de Endpoint',
                'verbose_name_plural': 'Métricas de Endpoints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint'], name='school_endp_endpoin_bc447e_idx'), models.Index(fields=['method'], name='school_endp_method_49eaa0_idx'), models.Index(fields=['status_code'], name='school_endp_status__922cb0_idx'), models.Index(fields=['created_at'], name='school_endp_created_5b60e2_idx')],
            },
        ),
    ]
