# Generated by Django 6.0.5 on 2026-05-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_external_id_student_parent_id_and_more'),
        ('transaction', '0002_alter_transaction_product_alter_transaction_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='student.student')),
            ],
        ),
    ]
