# Generated by Django 6.0.5 on 2026-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_nutritionfact'),
        ('student', '0004_alter_student_name_and_more'),
        ('transaction', '0005_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recarga',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['student', '-fecha'], name='transaction_student_e43f19_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', '-created_at'], name='transaction_student_57ca62_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_0b821d_idx'),
        ),
    ]
