# Generated by Django 6.0.5 on 2026-05-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_alter_parent_phone_e164_and_more'),
        ('product', '0003_nutritionfact'),
        ('student', '0004_alter_student_name_and_more'),
        ('transaction', '0005_alter_transaction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de aprobacion'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('PAID', 'Pagado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approval_token', models.CharField(db_index=True, help_text='Token para aprobar via link', max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recarga',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['student', '-fecha'], name='transaction_student_e43f19_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', '-created_at'], name='transaction_student_57ca62_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_0b821d_idx'),
        ),
        migrations.AddField(
            model_name='loan',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='parent.parent'),
        ),
        migrations.AddField(
            model_name='loan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='student.student'),
        ),
        migrations.AddField(
            model_name='loan',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan', to='transaction.transaction'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='transaction_status_d2b5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['parent', 'status'], name='transaction_parent__01abe9_idx'),
        ),
    ]
