# Generated by Django 6.0.5 on 2026-05-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('student', '0003_student_external_id_student_parent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(max_length=20, unique=True, verbose_name='Teléfono (E.164)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Padre')),
                ('students', models.ManyToManyField(related_name='parents', to='student.student', verbose_name='Estudiantes (Hijos)')),
            ],
            options={
                'verbose_name': 'Padre',
                'verbose_name_plural': 'Padres',
            },
        ),
        migrations.DeleteModel(
            name='ParentPhoneMap',
        ),
    ]
