# Generated by Django 6.0.5 on 2026-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_parent_delete_parentphonemap'),
        ('student', '0003_student_external_id_student_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_e164',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Teléfono (E.164)'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone_e164'], name='parent_pare_phone_e_9abd83_idx'),
        ),
    ]
