# Generated by Django 6.0.5 on 2026-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alertconfiguration'),
        ('student', '0003_student_external_id_student_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_stu_name_1fd404_idx'),
        ),
    ]
